### ISSUE TITLE
Sugestão 💡 

### ISSUE THREAD

**Issue by AldairAvelino** [AmandaAilin/ListaDeTarefas#1]
Fala Dev, como você está? Eu achei a tua ideia sensacional. A única coisa que eu quero acrescentar é que podes usar o LocalStorage para armazenares as informas da lista de atividades. Bom trabalho aí. 👍 
@AmandaAilin

**Comment by AmandaAilin** [comment]
@AldairAvelino 
Estou bem, valeu pela dica! recentemente fiz a atualização com Local Storage 😄

**Comment by AldairAvelino** [comment]
@AmandaAilin 
Bons estudos aí. 💪👊

**Comment by AldairAvelino** [comment]
👏💪👊
